version: "2"
services:
  www:
    build:
      context: ./www/
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
    networks:
      - default

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: phpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: root  
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    depends_on:
      - db

volumes:
  persistent: